### PR TITLE
[GH-#111] After adding a peer add his peers

### LINKED ISSUE #111: after adding a peer add his peers
- [x] get peers from other nodes to keep an preset number of peers in memory; Download peers from every peer, choose peers that we don't know, add to our list.
 - [x] add a maximum of 50 peers to add to the list, after that don't add any new ones

### PR DESCRIPTION
**Pull request by cheezus1**
closes #111

### CODE REVIEW

**Comment by cytadela8** [comment]
Hmm... I didn't know about this issue. This conflicts with my work on #115.

**Comment by cytadela8** [comment]
I suggest, I will try to propose an overall solution to peer sync this evening.

**Comment by thepiwo** [comment]
Yeah maybe it is conflicting, but we need both issues solved. Could you integrate these changes in your work?

**Comment by cytadela8** [comment]
@thepiwo I will try to do that this evening, but at the moment I think this PR conflicts with my design choices. I will try to think how to make everything work this evening and probably I will propose some solution.

**Comment by cytadela8** [comment]
After analysing possibilities I took the test fix and `max_peers` limit from this code. Sadly most of this code conflicts with peer sync design I would like to introduce with #123. Sorry for not realizing the conflict earlier!

**Comment by thepiwo** [comment]
@cytadela8 so we merge this, prior to #123?

**Comment by cytadela8** [comment]
@thepiwo We ignore this. I cherry-picked one commit and rewritten `max_peers`.

**Comment by thepiwo** [comment]
replaced with #123

**Pull request closed without merging**
