### PR TITLE
[GH-136] Persisting blocks by using RocksDB

### LINKED ISSUE #136: use rocksdb to read/write blocks by hash

### PR DESCRIPTION
**Pull request by meivantodorov**
### General description

Now we are using `RocksDB` instead of `dets` to write/read blocks by their hash. For that
purpose we added [Rox](https://hexdocs.pm/rox/api-reference.html) library.

`Rox` library needs [Rust to be installed.](https://rustup.rs/) 

Made some separations in the  `aecore` `priv` folder. Now `cuckoo` nifs and `rocksdb` are in different sub folders.

Closes #136

### CODE REVIEW

**Comment by cytadela8** [comment]
I get following error when trying to compile/run node. Am I missing some system dependency?
```
==> rox
Compiling NIF crate :rox_nif (native/rox_nif)...
could not compile dependency :rox, "mix compile" failed. You can recompile this dependency with "mix deps.compile rox", update it with "mix deps.update rox" or clean it with "mix deps.clean rox"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:605: System.cmd("cargo", ["rustc", "--no-default-features", "--release"], [cd: "/home/ert/aeternity/elixir-research/deps/rox/native/rox_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ert/aeternity/elixir-research/_build/dev/rustler_crates/rox_nif"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:53: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
```

**Comment by meivantodorov** [comment]
[Rust have to be installed.](https://rustup.rs/)

**Comment by cytadela8** [comment]
Also latest_block info isn't available.

```
iex(2)> Aecore.Chain.Worker.latest_block                                                                                                                                    
%Aecore.Structures.Block{header: %Aecore.Structures.Header{chain_state_hash: <<0,                                                                                           
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                              
    0, 0, 0, 0, 0, 0>>, difficulty_target: 1, height: 0, nonce: 62,                                                                                                         
  pow_evidence: [5865, 33461, 43503, 72290, 97096, 102579, 109935, 110807,                                                                                                  
   129404, 135480, 145736, 174409, 178611, 180359, 183866, 197227, 198055,                                                                                                  
   206373, 220794, 221908, 227792, 240266, 248610, 311225, 312038, 315739,                                                                                                  
   327595, 334270, 336439, 345186, 348916, 357090, 372159, 444132, 462404,                                                                                                  
   464127, 464504, 495627, 495985, 497109, 504460, 510965],                                                                                                                 
  prev_hash: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                            
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, timestamp: 1507275094308,                                                                                                               
  txs_hash: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, version: 1}, txs: []}
```
**note the height**

**Comment by meivantodorov** [comment]
We are not auto loading the latest block. We just write all blocks into the db.

**Comment by meivantodorov** [comment]
> So I understand restoring loading is in scope of another issue? 

Yes

**Pull request merged**
