### PR TITLE
[GH-144] Fixing Cuckoo

### LINKED ISSUE #144: fix Cuckoo Cycle crashes

### PR DESCRIPTION
**Pull request by meivantodorov**
Closes #144 

- NiF was replaced with port.
- Major changes on the miner worker.
- Some unit tests were refactored.

### CODE REVIEW

**Comment by untra** [comment]
> * NiF was replaced with port.
I think that is a smart call, as Erlang/otp tends to play better with data interacting through ports rather than calling native functions in different languages.

So then does this mean the cuckoo cycle runs as a separate service? If I have a cuda enabled gpu, will I be able to run the [cuda-enabled cuckoo cycle c code](https://github.com/tromp/cuckoo/blob/master/src/cuda_miner.cu) instead of the current .cpp NiF?

**Comment by meivantodorov** [comment]
@untra 
We start separately the miner from the vm as os process and we communicate with it via port.
As for the using gpu - at some point yes, for now we have not implemented it.

**Comment by thepiwo** [comment]
can you fix this in this branch? https://github.com/aeternity/elixir-research/issues/179 `{:error, _}` should do it

**Comment by thepiwo** [comment]
@cheezus1 @nedelcho-delchev-tues @d-velev @cytadela8 can you review this as well?

**Comment by thepiwo** [comment]
@meivantodorov ok merge this now?

**Comment by nedelcho-delchev-tues** [comment]
fixes #171

**Comment by meivantodorov** [comment]
@thepiwo I think it is okey to be merged, if something come up we can mange it later on.

**Comment by thepiwo** [comment]
ok @meivantodorov please merge :tada:

**Pull request merged**
