### PR TITLE
[GH-233] Address types 

### PR DESCRIPTION
**Pull request by cytadela8**
This is a proposal to add different address types. More description in #233 

Work-In-Progress

### CODE REVIEW

**Comment by thepiwo** [comment]
@gspasov @rdimitrovbg what do you think of this? More info is in issue #233

**Comment by thepiwo** [comment]
@cytadela8 are you ok with closing this in favor of changes proposed in https://github.com/aeternity/elixir-research/issues/203?

**Comment by thepiwo** [comment]
@cytadela8 are you ok with closing this in favor of changes proposed in #203?

**Comment by cytadela8** [comment]
not ready, tests fail

**Comment by thepiwo** [comment]
@cytadela8 tests don't fail on travis

**Pull request merged**
